### ISSUE TITLE
OCI SDK on Windows 7: Doesn't reslove private key location correctly

### ISSUE THREAD

**Issue by pblokhin-us** [oracle/oci-cli#161]
I have installed OCI SDK on my Windows laptop today, but I am unable to run any commands because the SDK doesn't resolve the location of private key correctly. It is looking under '/home/pblokhin/.oci/oci_api_key.pem', while on my Windows the home directory is c:\users\pblokhin.oradev, and the key file is under c:\users\pblokhin.oradev\.oci\oci_api_key.pem.
Below is the trace:

Traceback (most recent call last):
  File "C:\Users\pblokhin.ORADEV\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pblokhin.ORADEV\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pblokhin.ORADEV\bin\oci.exe\__main__.py", line 9, in <module>
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\click\core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci_cli\cli_util.py", line 1474, in internal_handle_param
    return _coalesce_param(ctx, param, value, required, explicit_default=default)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci_cli\cli_util.py", line 1491, in _coalesce_param
    value = coalesce_provided_and_default_value(ctx, hyphenated_param_name, value, required)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci_cli\cli_util.py", line 1197, in coalesce_provided_and_default_value
    client = build_client('object_storage', ctx)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci_cli\cli_util.py", line 393, in build_client
    client = client_class(client_config, **kwargs)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci\object_storage\object_storage_client.py", line 69, in __init__
    private_key_content=config.get("key_content")
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci\signer.py", line 226, in __init__
    self.private_key = load_private_key_from_file(private_key_file_location, pass_phrase)
  File "c:\users\pblokhin.oradev\lib\oracle-cli\lib\site-packages\oci\signer.py", line 27, in load_private_key_from_file
    with io.open(filename, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pblokhin/.oci/oci_api_key.pem'

**Comment by vish1** [comment]
@pblokhin-us Can you verify the private key file location in the CLI configuration file?

**Comment by pblokhin-us** [comment]
Thank you for responding. The location was incorrect, hence the error. With correct location, I am able to run the command but still not going too far:

. : File C:\Users\pblokhin.ORADEV\Documents\WindowsPowerShell\Microsoft.PowerSh
ell_profile.ps1 cannot be loaded because running scripts is disabled on this system. 

But this is a different error, and apparently related to my Windows machine setup. If you have any tips for me, please share. As far as the issue is concerned, I think we can close it.

**Comment by vish1** [comment]
@pblokhin-us See the Windows Section under https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliinstall.htm#InstallingtheCLI. Did you run this command: `Set-ExecutionPolicy RemoteSigned`

**Comment by pblokhin-us** [comment]
I was able to run the script after setting execution policy to "Unrestricted". Changed to "RemoteSigned" as you suggested, and it also works. Thanks for your help, I am good now.
