### ISSUE TITLE
setting up OCI CLI on mac, but the package dont install as expected. Getting the below error

### ISSUE THREAD

**Issue by udaykanamaneni** [oracle/oci-cli#183]
dhcp-10-159-254-207:ssh ukanaman_mac$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.5.15/scripts/install/install.py to /var/folders/sp/9h9hy7h126q0nxcnhw746mv00000gq/T/oci_cli_install_tmp_XXXX.iesH7Urf.
######################################################################## 100.0%
cat: /etc/os-release: No such file or directory
Running install script.
python3 /var/folders/sp/9h9hy7h126q0nxcnhw746mv00000gq/T/oci_cli_install_tmp_XXXX.iesH7Urf 
-- Verifying Python version.
-- Python version 3.7.3 okay.

===> In what directory would you like to place the install? (leave blank to use '/Users/ukanaman_mac/lib/oracle-cli'): 
-- We will install at '/Users/ukanaman_mac/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/Users/ukanaman_mac/bin'): 
-- The executable will be in '/Users/ukanaman_mac/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/Users/ukanaman_mac/bin/oci-cli-scripts'): 
-- The scripts will be in '/Users/ukanaman_mac/bin/oci-cli-scripts'.

===> Currently supported optional packages are: ['db (will install cx_Oracle)']
What optional CLI packages would you like to be installed (comma separated names; press enter if you don't need any optional packages)?: 
-- The optional packages installed will be ''.
-- Downloading virtualenv package from https://github.com/pypa/virtualenv/archive/15.0.0.tar.gz.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/sp/9h9hy7h126q0nxcnhw746mv00000gq/T/oci_cli_install_tmp_XXXX.iesH7Urf", line 141, in create_virtualenv
    response = urlopen(VIRTUALENV_DOWNLOAD_URL)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
ERROR: Failed to download virtualenv package. Please check that your trusted certificates are up to date and include the certificates necessary to verify github.com

Please help if anybody experienced the above issue.
Fyi.., i am using Mac Mojave

**Comment by paul-hummel-oracle** [comment]
@udaykanamaneni 
Please try running /Applications/Python 3.7/Install Certificates.command followed by running CLI Installer.

**Comment by udaykanamaneni** [comment]
Thank you Paul!!
This worked . appreciate your help
