### ISSUE TITLE
Announcements time types broken

### ISSUE THREAD

**Issue by LiamAtOracle** [oracle/oci-cli#194]
Looks like since the OCI update the data for Announcements is different. When retrieving the announcements via the oci cli. This also effects the python module.
OCI version: 2.6.1
OS: Mac os X

command:oci announce announcements list --compartment-id ocid1.tenancy.oc1..aaaaaaaa4lr6ivwmsh3ddhd7srz753iaz6ixyzb56uuq3tqw5shwl5y73z5q
TypeError: must be string, not int

With python module.

Traceback (most recent call last):
  File "bin/oci_tool.py", line 301, in <module>
    get_announcements(tenancy_nm,tenancy_id,compartments,announcements,ticket_announce,adsweb_config_file)
  File "bin/oci_tool.py", line 171, in get_announcements
    i = announcements.list_announcements(tenancy_id).data
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/announcements_service/announcement_client.py", line 370, in list_announcements
import urllib.request
    response_type="AnnouncementsCollection")
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 229, in call_api
    response = self.request(request)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 361, in request
    deserialized_data = self.deserialize_response_data(response.content, response_type)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 557, in deserialize_response_data
    res = self.__deserialize(response_data, response_type)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 600, in __deserialize
    return self.__deserialize_model(data, cls)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 673, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 577, in __deserialize
    for sub_data in data]
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 577, in <listcomp>
    for sub_data in data]
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 600, in __deserialize
    return self.__deserialize_model(data, cls)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 673, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 598, in __deserialize
    return self.__deserialize_datetime(data)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/oci/base_client.py", line 645, in __deserialize_datetime
    naivedatetime = datetime.strptime(string, "%Y-%m-%dT%H:%M:%S.%fZ")
TypeError: must be str, not int

**Comment by jodoglevy** [comment]
This is an issue in the announcements service, they are working on fixing it at the moment

**Comment by LiamAtOracle** [comment]
Do we know if that fix is annotated somewhere? Like in a ticket or communication?

**Comment by jodoglevy** [comment]
The announcements team today said they have fixed this issue. Closing this.
