### ISSUE TITLE
CLI installation fails on MacOS Mojave (Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib)

### ISSUE THREAD

**Issue by opichals** [oracle/oci-cli#226]
Error message

`Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

Complete output

```sh
$ bash -c "$(curl -s -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.6.12/scripts/install/install.py to /var/folders/2r/nrc2vjjj4b3657kp6pyt0q4m0000gn/T/oci_cli_install_tmp_XXXX.iaVzocQq.
######################################################################## 100.0%
cat: /etc/os-release: No such file or directory
Running install script.
python3 /var/folders/2r/nrc2vjjj4b3657kp6pyt0q4m0000gn/T/oci_cli_install_tmp_XXXX.iaVzocQq 
Traceback (most recent call last):
  File "/var/folders/2r/nrc2vjjj4b3657kp6pyt0q4m0000gn/T/oci_cli_install_tmp_XXXX.iaVzocQq", line 21, in <module>
    import ssl
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
```

System info and various attempts to find a solution:

* MacOS 10.14.6 (Mohave)
* $ uname -a
```Darwin xyz.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64```
 * `find . -name libssl\*.dylib` in `/usr` (Homebrew setup)
   ```sh
   $ cd /usr
   $ find . -name libssl\*.dylib
   ./local/Cellar/openssl@1.1/1.1.1d/lib/libssl.dylib
   ./local/Cellar/openssl@1.1/1.1.1d/lib/libssl.1.1.dylib
   ./local/Cellar/openssl/1.0.2r/lib/libssl.dylib
   ./local/Cellar/openssl/1.0.2r/lib/libssl.1.0.0.dylib
   ./lib/libssl.0.9.8.dylib
   ./lib/libssl.dylib
   ./lib/libssl.35.dylib
   ./lib/libssl.0.9.7.dylib
   ./lib/libssl.43.dylib
   ./lib/libssl.44.dylib

 * $ brew reinstall `openssl@1.0.2r`
`Error: No available formula with the name "openssl@1.0.2r" `

 * $ brew reinstall openssl
   ```
   ==> Reinstalling openssl@1.1 
   ==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1d.mojave.bottle.tar.gz
   Already downloaded: /Users/standa/Library/Caches/Homebrew/downloads/ad40ab0d39bcc1e58d4e87515460f704efd1   95352ae376f7b28994b71c640810--openssl@1.1-1.1.1d.mojave.bottle.tar.gz
   ==> Pouring openssl@1.1-1.1.1d.mojave.bottle.tar.gz
   ==> Summary
   🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,983 files, 17.9MB
   ```

**Comment by opichals** [comment]
Looks like it was a Homebrew issue. I did `brew reinstall python3` and the install went ok after that.
