### ISSUE TITLE
oci cli installation failure in Windows10 + Python3.8

### ISSUE THREAD

**Issue by OmSao** [oracle/oci-cli#245]
Hello Team,
**Environment detail**: Windows 10, 64 bit. Tried with Python 3.5, 3.6 and 3.8 (same behaviour).
Set my proxy and tested PowerShell for network working using "Invoke-WebRequest http://www.google.com"

**For installing oci-cli**
[](Following: https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm)

**In PowerShell Administrator mode**:

**PS C:\WINDOWS\system32>** Set-ExecutionPolicy RemoteSigned
**PS C:\WINDOWS\system32>** powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1'))"

**Here is the trace**:

**PS C:\WINDOWS\system32>** powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1'))"

        ******************************************************************************
        You have started the OCI CLI Installer in interactive mode. If you do not wish
        to run this in interactive mode, please include the -AcceptAllDefaults option.
        If you have the script locally and would like to know more about
        input options for this script, then you can run:
        help .\install.ps1
        If you would like to know more about input options for this script, refer to:
        https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
        ******************************************************************************
VERBOSE: Python found in registry: HKCU:\Software\Python\PythonCore
VERBOSE: Python found in registry: HKLM:\Software\Python\PythonCore
VERBOSE: Downloading install script to C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp
VERBOSE:  False   False
VERBOSE: Using Python executable: C:\Python38\python.exe to run install script...
VERBOSE: Arguments to python script: "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp"
-- Verifying Python version.
-- Python version 3.8.1 okay.

===> In what directory would you like to place the install? (leave blank to use 'C:\Users\OSAO.ORADEV\lib\oracle-cli'):
-- We will install at 'C:\Users\OSAO.ORADEV\lib\oracle-cli'.

===> In what directory would you like to place the 'oci.exe' executable? (leave blank to use 'C:\Users\OSAO.ORADEV\bin'):
-- The executable will be in 'C:\Users\OSAO.ORADEV\bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use 'C:\Users\OSAO.ORADEV\bin\oci-cli-scripts'):
-- The scripts will be in 'C:\Users\OSAO.ORADEV\bin\oci-cli-scripts'.

===> Currently supported optional packages are: ['db (will install cx_Oracle)']
What optional CLI packages would you like to be installed (comma separated names; press enter if you don't need any optional packages)?:
-- The optional packages installed will be ''.
-- Downloading virtualenv package from https://github.com/pypa/virtualenv/archive/15.0.0.tar.gz.
Traceback (most recent call last):
  File "C:\Python38\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Python38\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Python38\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp", line 654, in <module>
    main()
  File "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp", line 609, in main
    create_virtualenv(tmp_dir, install_dir)
  File "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp", line 145, in create_virtualenv
    raise e
  File "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp", line 139, in create_virtualenv
    response = urlopen(VIRTUALENV_DOWNLOAD_URL)
  File "C:\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python38\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1')) : Executing C:\Python38\python.exe "C:\Users\OSAO.ORADEV\AppData\Local\Temp\tmpD339.tmp"
returned a non-zero exit code.

At line:381 char:9
+         Write-Error "Executing $PythonExecutable $ArgumentList return ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

At line number 381: of install.py(https://github.com/oracle/oci-cli/blob/master/scripts/install/install.py)

Any Suggestions ?

**Comment by OmSao** [comment]
The issue got resolved, when I followed same steps from PowerShell after:
0. Launched command from my home network instead from behind corporate proxy.
1. Removing http(s)_proxy from Environment variables.
2. Removing proxy from from Powershell env variables.
3. Removing browser proxy.

Closing the issue.
