### ISSUE TITLE
Cannot create multiple objects using a single JSON file. i.e. multiple VCNs in the same compartment 

### ISSUE THREAD

**Issue by danxtrate** [oracle/oci-cli#247]
I tried to create multiple VCNs in a single compartment using a single JSON file. 
Is there a limitation in OCI CLI? My JSON files passes JSON validation. 

Here is a sample of my code: 
First try: 

Here OCI CLI returns: 

> Missing Options --cidr-block, --compartment-id

Which makes me think that OCI CLI does not like data structures. 

```
{
	"data": [{
			"cidrBlock": "10.0.0.0/16",
			"compartmentId": "ocid1.compartment.oc1..aaaaaaaad7rypzrctvmlzbnfxlte2wxq3cenxipjje6b6erpat36sca2qh3a",
			"definedTags": {},
			"displayName": "groupvcn1",
			"dnsLabel": "groupvcn1",
			"freeformTags": {},
			"ipv6CidrBlock": null,
			"isIpv6Enabled": null,
			"maxWaitSeconds": 0,
			"waitForState": [
				"AVAILABLE"
			],
			"waitIntervalSeconds": 0
		},
		{
			"cidrBlock": "10.0.0.0/16",
			"compartmentId": "ocid1.compartment.oc1..aaaaaaaad7rypzrctvmlzbnfxlte2wxq3cenxipjje6b6erpat36sca2qh3a",
			"definedTags": {},
			"displayName": "groupvcn2",
			"dnsLabel": "groupvcn2",
			"freeformTags": {},
			"ipv6CidrBlock": null,
			"isIpv6Enabled": null,
			"maxWaitSeconds": 0,
			"waitForState": [
				"AVAILABLE"
			],
			"waitIntervalSeconds": 0
		}
	]
}
```

Second try:
I tried to define more objects here, Same error as above. 

```
{
  "vcn1":
      {
      "cidrBlock": "10.0.0.0/16",
      "compartmentId": "ocid1.compartment.oc1..aaaaaaaad7rypzrctvmlzbnfxlte2wxq3cenxipjje6b6erpat36sca2qh3a",
      "definedTags": {},
      "displayName": "groupvcn1",
      "dnsLabel": "groupvcn1",
      "freeformTags": {},
      "ipv6CidrBlock": null,
      "isIpv6Enabled": null,
      "maxWaitSeconds": 0,
      "waitForState": [
        "AVAILABLE"
      ],
      "waitIntervalSeconds": 0
    },
    "vcn2":
    {
      "cidrBlock": "10.0.0.0/16",
      "compartmentId": "ocid1.compartment.oc1..aaaaaaaad7rypzrctvmlzbnfxlte2wxq3cenxipjje6b6erpat36sca2qh3a",
      "definedTags": {},
      "displayName": "groupvcn2",
      "dnsLabel": "groupvcn2",
      "freeformTags": {},
      "ipv6CidrBlock": null,
      "isIpv6Enabled": null,
      "maxWaitSeconds": 0,
      "waitForState": [
        "AVAILABLE"
      ],
      "waitIntervalSeconds": 0
    }

}
```
When debugging the last command this is what I get: 
```
Traceback (most recent call last):
  File "/home/opc/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/oci_cli/json_skeleton_utils.py", line 82, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/home/opc/lib/oracle-cli/lib/python3.6/site-packages/oci_cli/cli_util.py", line 718, in wrapped_call
    raise cli_exceptions.RequiredValueNotInDefaultOrUserInputError('Missing option(s) --{}.'.format(', --'.join(ctx.obj['missing_required_parameters'])))
oci_cli.cli_exceptions.RequiredValueNotInDefaultOrUserInputError: Missing option(s) --cidr-block, --compartment-id.

```

**Comment by srikanthkumbham** [comment]
@danxtrate OCI CLI doesn't support creating multiple resources using the single create command. I'll file a feature request for this internally and meanwhile, you could write a simple bash script to achieve the same result.
