### ISSUE TITLE
Caused by NewConnectionError with oci network vcn create

### ISSUE THREAD

**Issue by torstenboe** [oracle/oci-cli#261]
When I run "oci network vcn create" I always get the following error message: 

RequestException: HTTPSConnectionPool(host='iaas.--dns-label.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd611d87e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Looks like a connection problem, but all other oci commands run fine. When I run the same command twice, the second time it succeeds. the complete command looks like that:

    VCN=$(oci network vcn create \
    --wait-for-state AVAILABLE \
    --cidr-block 10.0.0.0/24 \
    --compartment-id $COMPARTMENT \
    --region $LOCATION \
    --dns-label "${DNSLABEL}" \
    --display-name "${PROJECT_}VCN" | jq --raw-output .data.id)

**Comment by vish1** [comment]
@torstenboe Looks like the hostname might not be correct for the request. `'iaas.--dns-label.oraclecloud.com`. Can you run the command in debug mode `--debug` both times and capture the output? Thanks!

**Comment by torstenboe** [comment]
Here is the output when it fails:

INFO:oci.base_client.140100346797136: 2020-03-13 07:10:01.318501: Request: POST https://iaas.--dns-label.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140100346797136: 2020-03-13 07:10:11.579524: Request: POST https://iaas.--dns-label.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140100346797136: 2020-03-13 07:10:23.972677: Request: POST https://iaas.--dns-label.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140100346797136: 2020-03-13 07:10:37.020544: Request: POST https://iaas.--dns-label.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140100346797136: 2020-03-13 07:11:00.393126: Request: POST https://iaas.--dns-label.oraclecloud.com/20160918/vcns
Traceback (most recent call last):
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 163, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 604, in urlopen
    chunked=chunked)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 347, in _make_request
    self._validate_conn(conn)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 305, in connect
    conn = self._new_conn()
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
oci._vendor.urllib3.exceptions.NewConnectionError: <oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ba7675e48>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/requests/adapters.py", line 454, in send
    enforce_content_length=True
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 642, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/urllib3/util/retry.py", line 402, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
oci._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='iaas.--dns-label.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ba7675e48>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/base_client.py", line 347, in request
    timeout=self.timeout)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/requests/sessions.py", line 537, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/requests/sessions.py", line 650, in send
    r = adapter.send(request, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/requests/adapters.py", line 521, in send
    raise ConnectionError(e, request=request)
oci._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='iaas.--dns-label.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ba7675e48>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/torsten/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/json_skeleton_utils.py", line 82, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/cli_util.py", line 733, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/services/core/src/oci_cli_virtual_network/generated/virtualnetwork_cli.py", line 2708, in create_vcn
    **kwargs
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/core/virtual_network_client.py", line 3893, in create_vcn
    response_type="Vcn")
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/retry/retry.py", line 271, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/base_client.py", line 239, in call_api
    response = self.request(request)
  File "/home/torsten/lib/oracle-cli/lib64/python3.6/site-packages/oci/base_client.py", line 356, in request
    raise exceptions.RequestException(e)

**Comment by torstenboe** [comment]
Thank you! The response showed a different variable. In changed it from local to global and now everything is fine.

**Comment by vish1** [comment]
@torstenboe Glad to know the issue got resolved. If you can provide more detailed info about the problem and resolution, it might help others.
