### ISSUE TITLE
Unable to launch CLI on MAC

### ISSUE THREAD

**Issue by ashishjainm** [oracle/oci-cli#293]
I get the following error after installing CLI following the instructions on this page: https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm

Below is the error:

Traceback (most recent call last):
  File "/Users/ashishjain/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/__init__.py", line 39, in <module>
    from .cli_root import cli  # noqa: F401,E402
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_root.py", line 18, in <module>
    from . import cli_util
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_util.py", line 39, in <module>
    from .cli_clients import CLIENT_MAP, MODULE_TO_TYPE_MAPPINGS
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_clients.py", line 29, in <module>
    oci_cli_module = __import__(ALL_SERVICES_DIR + '.' + modname1 + '.src.' + oci_cli_module_name)
ModuleNotFoundError: No module named 'services.analytics'

**Comment by vish1** [comment]
@ashishjainm I followed the same steps and was able to install the CLI and verify that it is working correctly. Can you provide more details - installation logs and how you are invoking the CLI?

**Comment by ashishjainm** [comment]
@vish1 can you please let me know where i can find the logs?
Also, i am trying to launch the cli from a terminal window on mac.
I am using a conda virtual env which i initialize with the following command:
conda activate py36 (this is a python 3.6 environment).
But i think it is using python 3.7 installed on the mac.

**Comment by ashishjainm** [comment]
```
Ashishs-MacBook-Pro-2:~ ashishjain$ bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14738  100 14738    0     0  40378      0 --:--:-- --:--:-- --:--:-- 40267

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.9.3/scripts/install/install.py to /var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/oci_cli_install_tmp_XXXX.5xwqU0ii.
################################################################################################################################################################################ 100.0%
cat: /etc/os-release: No such file or directory
Running install script.
python3 /var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/oci_cli_install_tmp_XXXX.5xwqU0ii 
-- Verifying Python version.
-- Python version 3.7.6 okay.

===> In what directory would you like to place the install? (leave blank to use '/Users/ashishjain/lib/oracle-cli'): 
-- Install directory '/Users/ashishjain/lib/oracle-cli' is not empty and may contain a previous installation.

===> Remove this directory? (y/N): y
-- Deleted '/Users/ashishjain/lib/oracle-cli'.
-- Creating directory '/Users/ashishjain/lib/oracle-cli'.
-- We will install at '/Users/ashishjain/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/Users/ashishjain/bin'): 
-- The executable will be in '/Users/ashishjain/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/Users/ashishjain/bin/oci-cli-scripts'): 
-- The scripts will be in '/Users/ashishjain/bin/oci-cli-scripts'.

===> Currently supported optional packages are: ['db (will install cx_Oracle)']
What optional CLI packages would you like to be installed (comma separated names; press enter if you don't need any optional packages)?: db
-- The optional packages installed will be 'db'.
-- Trying to use python3 venv.
-- Executing: ['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3', '-m', 'venv', '/Users/ashishjain/lib/oracle-cli']
-- Executing: ['/Users/ashishjain/lib/oracle-cli/bin/pip', 'install', '--upgrade', 'pip']
Collecting pip
  Using cached https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.1.1
-- Executing: ['/Users/ashishjain/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6', 'wheel', '--upgrade']
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2
-- Executing: ['/Users/ashishjain/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6', 'oci_cli[db]', '--upgrade']
Collecting oci_cli[db]
  Downloading oci_cli-2.11.1-py2.py3-none-any.whl (8.3 MB)
     |████████████████████████████████| 8.3 MB 180 kB/s 
Collecting oci==2.16.1
  Downloading oci-2.16.1-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 224 kB/s 
Collecting click==6.7
  Downloading click-6.7-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 335 kB/s 
Collecting configparser==4.0.2
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting jmespath==0.9.4
  Downloading jmespath-0.9.4-py2.py3-none-any.whl (24 kB)
Collecting cryptography==2.8
  Downloading cryptography-2.8-cp34-abi3-macosx_10_6_intel.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 369 kB/s 
Collecting arrow==0.14.7
  Downloading arrow-0.14.7-py2.py3-none-any.whl (39 kB)
Collecting terminaltables==3.1.0
  Downloading terminaltables-3.1.0.tar.gz (12 kB)
Collecting retrying==1.3.3
  Downloading retrying-1.3.3.tar.gz (10 kB)
Collecting python-dateutil<3.0.0,>=2.5.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 199 kB/s 
Collecting six==1.14.0
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting pytz>=2016.10
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 236 kB/s 
Collecting idna<2.7,>=2.5
  Downloading idna-2.6-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 455 kB/s 
Collecting certifi
  Downloading certifi-2020.4.5.2-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 382 kB/s 
Collecting pyOpenSSL==18.0.0
  Downloading pyOpenSSL-18.0.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 539 kB/s 
Collecting PyYAML==5.1.2
  Downloading PyYAML-5.1.2.tar.gz (265 kB)
     |████████████████████████████████| 265 kB 403 kB/s 
Collecting cx-Oracle==7.0; extra == "db"
  Downloading cx_Oracle-7.0.0.tar.gz (281 kB)
     |████████████████████████████████| 281 kB 326 kB/s 
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp37-cp37m-macosx_10_9_x86_64.whl (174 kB)
     |████████████████████████████████| 174 kB 189 kB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 150 kB/s 
Building wheels for collected packages: terminaltables, retrying, PyYAML, cx-Oracle
  Building wheel for terminaltables (setup.py) ... done
  Created wheel for terminaltables: filename=terminaltables-3.1.0-py3-none-any.whl size=15354 sha256=49dd55cd136ddf2b565bc45c7dec271e0a697281eb1972265516cf3cb0e68442
  Stored in directory: /private/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6/wheels/ba/ad/c8/2d98360791161cd3db6daf6b5e730f34021fc9367d5879f497
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11430 sha256=58d767d297eba284c2918448fc5881bd3c4e8413e0c1fff4a6ebf4d32cb4819f
  Stored in directory: /private/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.1.2-cp37-cp37m-macosx_10_9_x86_64.whl size=44109 sha256=2b1998ffa795a913e4f127bc91d9997d35b833debc19a9a44fabaa6bd4f334b0
  Stored in directory: /private/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6/wheels/23/b9/73/57aaccb6957d94ed63f474b51a9f7f992c5eff4635052c0557
  Building wheel for cx-Oracle (setup.py) ... done
  Created wheel for cx-Oracle: filename=cx_Oracle-7.0.0-cp37-cp37m-macosx_10_9_x86_64.whl size=157721 sha256=01c0ae3baa7d5e366e834b6790ab812a566b1a15fda562dfdafebf1d18f0989e
  Stored in directory: /private/var/folders/r0/x8jcz_3j65z1_1qsmmdrgjdr0000gn/T/tmpmhsb8pd6/wheels/71/67/ad/9209d31845e7a6ff4d228817d0a18b69aeabaed7f8dd22cc2f
Successfully built terminaltables retrying PyYAML cx-Oracle
Installing collected packages: configparser, six, pycparser, cffi, cryptography, pyOpenSSL, python-dateutil, pytz, certifi, oci, click, jmespath, arrow, terminaltables, retrying, idna, PyYAML, cx-Oracle, oci-cli
Successfully installed PyYAML-5.1.2 arrow-0.14.7 certifi-2020.4.5.2 cffi-1.14.0 click-6.7 configparser-4.0.2 cryptography-2.8 cx-Oracle-7.0.0 idna-2.6 jmespath-0.9.4 oci-2.16.1 oci-cli-2.11.1 pyOpenSSL-18.0.0 pycparser-2.20 python-dateutil-2.8.1 pytz-2020.1 retrying-1.3.3 six-1.14.0 terminaltables-3.1.0

===> Modify profile to update your $PATH and enable shell/tab completion now? (Y/n): Y

===> Enter a path to an rc file to update (leave blank to use '/Users/ashishjain/.bash_profile'): 
-- Backed up '/Users/ashishjain/.bash_profile' to '/Users/ashishjain/.bash_profile.backup'
-- Tab completion set up complete.
-- If tab completion is not activated, verify that '/Users/ashishjain/.bash_profile' is sourced by your shell.
-- 
-- ** Run `exec -l $SHELL` to restart your shell. **
-- 
-- Installation successful.
-- Run the CLI with /Users/ashishjain/bin/oci --help
Ashishs-MacBook-Pro-2:~ ashishjain$ exec -l $SHELL

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) Ashishs-MacBook-Pro-2:~ ashishjain$ conda deactivate
Ashishs-MacBook-Pro-2:~ ashishjain$ /Users/ashishjain/bin/oci --help
Traceback (most recent call last):
  File "/Users/ashishjain/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/__init__.py", line 39, in <module>
    from .cli_root import cli  # noqa: F401,E402
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_root.py", line 18, in <module>
    from . import cli_util
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_util.py", line 39, in <module>
    from .cli_clients import CLIENT_MAP, MODULE_TO_TYPE_MAPPINGS
  File "/Users/ashishjain/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_clients.py", line 29, in <module>
    oci_cli_module = __import__(ALL_SERVICES_DIR + '.' + modname1 + '.src.' + oci_cli_module_name)
ModuleNotFoundError: No module named 'services.analytics'
Ashishs-MacBook-Pro-2:~ ashishjain$ 

```

**Comment by ashishjainm** [comment]
okay figured it out.

I had a environment variable set in the .bash_profile file - PYTHONPATH
once i commented that, it started to work.

is the oci-cli using this variable in some form?

**Comment by adizohar** [comment]
If this works well, do you still need to leave the ticket open ?

**Comment by ashishjainm** [comment]
No. you can close it.

**Comment by adizohar** [comment]
I don’t have permission to close it, only admin or the ticket owner can do , thank you
