### ISSUE TITLE
osms attach timeout

### ISSUE THREAD

**Issue by chris93111** [oracle/oci-cli#313]
Hi 

I try to attach instance to group osms in oci but i have always timeout

i am directly plug in internet (no proxy)

oci os-management managed-instance-group attach --managed-instance-group-id xxxxxx--managed-instance-id xxxxx -d

Traceback (most recent call last):
  File "/Users/chris/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/json_skeleton_utils.py", line 83, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/cli_util.py", line 749, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/services/os_management/src/oci_cli_os_management/generated/osmanagement_cli.py", line 158, in attach_managed_instance_to_managed_instance_group
    **kwargs
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/os_management/os_management_client.py", line 333, in attach_managed_instance_to_managed_instance_group
    header_params=header_params)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/retry/retry.py", line 272, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/base_client.py", line 265, in call_api
    response = self.request(request)
  File "/Users/chris/lib/oracle-cli/lib/python3.7/site-packages/oci/base_client.py", line 371, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='osms.eu-frankfurt-1.oci.oraclecloud.com', port=443): Read timed out. (read timeout=60.0)

}[chris@MBP-de-FERREIRA:~ ] $ curl https://osms.eu-frankfurt-1.oci.oraclecloud.com/
{
  "code" : "NotAuthorizedOrNotFound",
  "message" : "Authorization failed or requested resource not found."
}[chris@MBP-de-FERREIRA:~ ] $ 

i tryed to set the timeout to 120 , result is same

the detach work correctly 
sometime i have 502 bad gateway with attach 

reply: 'HTTP/1.1 502 Bad Gateway\r\n'

header: Date: Mon, 27 Jul 2020 17:45:36 GMT

header: opc-request-id: 541DCFEA1B2E4902A22E8DE7DB317601/0F45AC295A44882B934F764C798616A6/E9C4C28BABB61EDDD329B2B12359A5CA

header: X-Content-Type-Options: nosniff

header: Cache-Control: must-revalidate,no-cache,no-store

header: Content-Length: 0

DEBUG:oci.base_client.4512110416: 2020-07-27 17:48:36.742031: time elapsed for request 541DCFEA1B2E4902A22E8DE7DB317601: 180.777110089

DEBUG:oci.base_client.4512110416: 2020-07-27 17:48:36.742718: Response status: 502

DEBUG:oci.base_client.4512110416: 2020-07-27 17:48:36.742997: python SDK time elapsed for deserializing: 2.515499997457482e-05

**Comment by kernleee** [comment]
@chris93111 Hi Chris, this error code seems like an authentication issue. Do you have all of the correct permissions or if this being run within a compute instance without enough permissions?

**Comment by chris93111** [comment]
Hi the user is admin of tenant , sometime the instance is attached but the return code of api is same 502

**Comment by kernleee** [comment]
Is there more to the debug log? A 502 error seems related to something on the user client. Do you have proxy environment variables set up possibly?

**Comment by chris93111** [comment]
No i am plug with internet directly , detach work perfectly

**Comment by kernleee** [comment]
Can you try the command again and give me a recent opc-request-id. I can request for the os management service to take a look into the specific api request. Do you have env variables for http_proxy or https_proxy?

**Comment by chris93111** [comment]
Hi no i don't have var http_proxy because i don't use proxy, i have plug directly to internet 

opc-request-id: E242F0FD847241A6BCA945C4A6133AD2

i have updated agent osms to latetest in instance (450) but the result is the same:
attach -> timeout or 502
detach -> work perfectly

**Comment by kernleee** [comment]
@chris93111 I'm working with the service team. Can you give me additional information
Region
Operating System Version

**Comment by chris93111** [comment]
Hi @kernleee 

"regionIdentifier" : "eu-frankfurt-1"
Oracle Linux Server release 7.5

**Comment by kernleee** [comment]
@chris93111 Hey, sorry about this, but the service team at minimum also requires a tenancy/instance id to troubleshoot the issue. I don't want the information to posted here on github. Is there a way for you to open a support ticket against Oracle if you work with support engineers? Or you can send it directly to my email kern.lee@oracle.com if you're comfortable doing so.
Ticket is being tracked internally as OSMS-4621

**Comment by kernleee** [comment]
Internal ticket has been closed from no response, I'll be closing this as well for now. Feel free to reopen if you continue to face issues.
