### ISSUE TITLE
Lacking "friendly" error message for oci compute launch

### ISSUE THREAD

**Issue by MarcinZablocki** [oracle/oci-cli#32]
$ oci compute instance launch

Traceback (most recent call last):
  File "/usr/local/bin/oci", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/oci_cli/json_skeleton_utils.py", line 58, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/oci_cli/core_cli_extended.py", line 445, in launch_instance_extended
    kwargs['availability_domain'] = cli_util.coalesce_provided_and_default_value(ctx, 'availability-domain', kwargs.get('availability_domain'), True)
  File "/Library/Python/2.7/site-packages/oci_cli/cli_util.py", line 767, in coalesce_provided_and_default_value
    raise cli_exceptions.RequiredValueNotInDefaultOrUserInputError('Missing option "--{}".'.format(param_name))
oci_cli.cli_exceptions.RequiredValueNotInDefaultOrUserInputError: Missing option "--availability-domain".

**Comment by nathan-vu** [comment]
Hi,

Which version (`oci --version`) of the CLI are you running? This is an issue we fixed in later versions of the CLI; for example in v2.4.13 (which we released yesterday) the messaging now becomes:

```
nvu-Mac:~ nvu$ /Users/nvu/bin/oci --version
2.4.13
nvu-Mac:~ nvu$ /Users/nvu/bin/oci compute instance launch
Usage: oci compute instance launch [OPTIONS]

Error: Missing option(s) --availability-domain, --compartment-id, --shape.
```

**Comment by MarcinZablocki** [comment]
@nathan-vu You're right. I didn't noticed the new release, pip uninstall, pip install resolved the problem. Thanks!
