### ISSUE TITLE
Max retries exceeded with url while doing oci network vcn list

### ISSUE THREAD

**Issue by aknadgir** [oracle/oci-cli#358]
I am trying to do:
```oci network vcn list --compartment-id 'ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq' --display-name integ-management```

But I keep getting error as:
```
RequestException: HTTPSConnectionPool(host='iaas.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns?compartmentId=ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq&displayName=integ-management (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f97cebf1c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

But when I run the same on Oracle cloud shell, it works perfectly fine. As suggested in one of other issues, I tried with --debug and here is the output of it:
```
-bash-4.1$ oci network vcn list --compartment-id 'ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq' --display-name integ-management --debug
INFO:oci.base_client.140290663349048: 2021-01-11 18:32:12.185367: Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140290663349048: 2021-01-11 18:32:12.439237: Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140290663349048: 2021-01-11 18:32:14.425420: Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140290663349048: 2021-01-11 18:32:16.604742: Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/vcns
INFO:oci.base_client.140290663349048: 2021-01-11 18:32:30.589813: Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/vcns
Traceback (most recent call last):
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 163, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 604, in urlopen
    chunked=chunked)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 347, in _make_request
    self._validate_conn(conn)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 305, in connect
    conn = self._new_conn()
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
oci._vendor.urllib3.exceptions.NewConnectionError: <oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f97f7277ef0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/requests/adapters.py", line 454, in send
    enforce_content_length=True
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/connectionpool.py", line 642, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/urllib3/util/retry.py", line 402, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
oci._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='iaas.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns?compartmentId=ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq&displayName=integ-management (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f97f7277ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/base_client.py", line 347, in request
    timeout=self.timeout)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/requests/sessions.py", line 537, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/requests/sessions.py", line 650, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/_vendor/requests/adapters.py", line 521, in send
    raise ConnectionError(e, request=request)
oci._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='iaas.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns?compartmentId=ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq&displayName=integ-management (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f97f7277ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci_cli/json_skeleton_utils.py", line 82, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci_cli/cli_util.py", line 733, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/services/core/src/oci_cli_virtual_network/generated/virtualnetwork_cli.py", line 6840, in list_vcns
    **kwargs
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/core/virtual_network_client.py", line 11856, in list_vcns
    response_type="list[Vcn]")
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/retry/retry.py", line 271, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/base_client.py", line 239, in call_api
    response = self.request(request)
  File "/usr/local/bin/oracle-cli/lib/python3.6/site-packages/oci/base_client.py", line 356, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='iaas.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/vcns?compartmentId=ocid1.compartment.oc1..aaaaaaaaq3r56dkkwmuudxtz6gfpsdbhbbjmtoi6xc5skoaxxp274udrd4qq&displayName=integ-management (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f97f7277ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
-bash-4.1$
```

I am running on Linux with
> oci --version
2.17.0

**Comment by harshkumar-dev** [comment]
Hi Akshay, 
Could you please setting up these 2 proxy variable with appropriate values and try again.

export http_proxy= <your organization's proxy url>
export https_proxy= <your organization's proxy url>

**Comment by vish1** [comment]
Most likely cause of the issue is that there is no route to the host `iaas.us-phoenix-1.oraclecloud.com`. Please verify that accessing the host via curl/wget works. Closing the issue due to no response. If this still exists, please reopen.
