### ISSUE TITLE
KeyError when creating kubeconfig

### ISSUE THREAD

**Issue by MartijnDwars** [oracle/oci-cli#374]
I installed the OCI CLI on Oracle Linux 7.9 by following the [Quickstart](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm#Quickstart) guide:

```
bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
```

I then added `$HOME/bin` to my `$PATH`. When I try to use the OCI CLI to create Kubeconf I get the following:

```
> oci ce cluster create-kubeconfig --cluster-id <snip> --file $HOME/.kube/config --region us-phoenix-1 --token-version 2.0.0
KeyError: 'clusters'
```

Other commands like `oci ce cluster list --compartment-id <snip>` and `oci iam compartment list --all` do work. What am I doing wrong? Is this a bug?

Versions:
```
> cat /etc/oracle-release
Oracle Linux Server release 7.9

> /home/<snip>/lib/oracle-cli/bin/python3.9 --version
Python 3.9.1

> oci -version
2.21.1
```

When running with `--debug` I get this stack trace:

```
Traceback (most recent call last):
  File "<snip $HOME>/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/oci_cli/json_skeleton_utils.py", line 83, in wrapped_call
    func(ctx, *args, **kwargs)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/oci_cli/cli_util.py", line 763, in wrapped_call
    func(ctx, *args, **kwargs)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/services/container_engine/src/oci_cli_container_engine/containerengine_cli_extended.py", line 313, in create_kubeconfig
    _merge_kubeconfig(new_kubeconfig, file)
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/services/container_engine/src/oci_cli_container_engine/containerengine_cli_extended.py", line 344, in _merge_kubeconfig
    _merge_kubeconfig_yaml(existing_kubeconfig_yaml, new_kubeconfig_yaml, 'clusters')
  File "<snip $HOME>/lib/oracle-cli/lib/python3.9/site-packages/services/container_engine/src/oci_cli_container_engine/containerengine_cli_extended.py", line 358, in _merge_kubeconfig_yaml
    for idx, j in enumerate(tmp_yaml[merge_key]):
KeyError: 'clusters'
```

**Comment by MartijnDwars** [comment]
Fixed. A file `~/.kube/config` already existed with the following contents:

```
apiVersion: v1
kind: Config
preferences: {}
```

After removing this file I could run the `oci ce cluster create-kubeconfig` successfully. Would be good if the OCI CLI gave a more descriptive error.

**Comment by harshkumar-dev** [comment]
Thanks Martjin. We will try to produce more description error in our future release.
