### ISSUE TITLE
No matching distribution found for cffi

### ISSUE THREAD

**Issue by Gharorcl** [oracle/oci-cli#458]
during offline install on ExaC@C DomU, 
[root@vm02 install]# **bash install.sh --offline-install**

Starting OCI CLI Offline Installation
System version of Python must be a Python 3 version >= 3.6.0.
Running install script.
python3 ./install.py  --offline-install
-- Verifying Python version.
-- Python version 3.6.8 okay.
 
===> In what directory would you like to place the install? (leave blank to use '/root/lib/oracle-cli'):
-- Install directory '/root/lib/oracle-cli' is not empty and may contain a previous installation.
 
===> Remove this directory? (y/N): y
-- Deleted '/root/lib/oracle-cli'.
-- Creating directory '/root/lib/oracle-cli'.
-- We will install at '/root/lib/oracle-cli'.
 
===> In what directory would you like to place the 'oci' executable? (leave blank to use '/root/bin'):
-- The executable will be in '/root/bin'.
 
===> In what directory would you like to place the OCI scripts? (leave blank to use '/root/bin/oci-cli-scripts'):
-- The scripts will be in '/root/bin/oci-cli-scripts'.
-- Trying to use python3 venv.
-- Executing: ['/bin/python3', '-m', 'venv', '/root/lib/oracle-cli']
-- Executing: ['/root/lib/oracle-cli/bin/pip', 'install', 'cffi', '--find-links', 'cli-deps', '--no-index']
Collecting cffi
  Url 'cli-deps' is ignored. It is either a non-existing path or lacks a specific scheme.
  Could not find a version that satisfies the requirement cffi (from versions: )
**No matching distribution found for cffi**
Traceback (most recent call last):
  File "./install.py", line 722, in <module>
    main()
  File "./install.py", line 677, in main
    install_cli(install_dir, tmp_dir, cli_version, OPTIONAL_FEATURES)
  File "./install.py", line 311, in install_cli
    exec_command(cmd, env=env)
  File "./install.py", line 141, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/lib/oracle-cli/bin/pip', 'install', 'cffi', '--find-links', 'cli-deps', '--no-index']' returned non-zero exit status 1.

**Comment by lealex262** [comment]
What is the name of the zip file you running on? There are zip files specifically for offline install
