### ISSUE TITLE
PDB remote-clone fails claiming CDB password is missing (when it is present)

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-cli#549]
```
$ oci db pluggable-database remote-clone --auth "api_key" --target-container-database-id "ocid1.database.oc1.iad.anuwcljsnlpusgyxm6m2tfvbrqh7q6utyabotijke2gt7a6a5vciu5ayacsa" --source-container-db-admin-password "PA55word-#" --cloned-pdb-name "TESTCL" --pluggable-database-id "ocid1.pluggabledatabase.oc1.iad.anuwcljsnlpusgyagnxfelnwycwqdn7m764ynvzk6lzyliy7rcylndhcjhpn" --pdb-admin-password "PA55word-#" --target-tde-wallet-password "PA55word-#" --is-pdb-admin-acc-locked false --debug
```

```
DEBUG:oci_cli.cli_metrics: 2022-04-22 15:41:49.594040: Metrics is not enabled
macOS-12.3.1-x86_64-i386-64bit
System name: Darwin
System release : 21.4.0
System version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64

env OCI_CLI_PROFILE is set
env OCI_GO_SDK_DEBUG is set
env OCI_PYTHON_SDK_NO_SERVICE_IMPORTS is set
DEBUG:oci_cli.cli_util:Config File: dict_keys(['log_requests', 'additional_user_agent', 'pass_phrase', 'user', 'fingerprint', 'key_file', 'tenancy', 'region'])
DEBUG:oci_cli.cli_util:region: Environment Variable or Parameter
DEBUG:oci.base_client.4415275312:Endpoint: https://database.us-ashburn-1.oraclecloud.com/20160918
INFO:oci.base_client.4415275312: 2022-04-22 15:41:49.700108: Request: POST https://database.us-ashburn-1.oraclecloud.com/20160918/pluggableDatabases/ocid1.pluggabledatabase.oc1.iad.anuwcljsnlpusgyagnxfelnwycwqdn7m764ynvzk6lzyliy7rcylndhcjhpn/actions/remoteClone
Not using Expect header...
send: b'POST /20160918/pluggableDatabases/ocid1.pluggabledatabase.oc1.iad.anuwcljsnlpusgyagnxfelnwycwqdn7m764ynvzk6lzyliy7rcylndhcjhpn/actions/remoteClone HTTP/1.1\r\nuser-agent: Oracle-PythonSDK/2.64.0 (python 3.10.2; x86_64-Darwin) Oracle-PythonCLI/3.7.3\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nopc-request-id: 028ECE46D3B842C4A21545386BAE4841\r\nopc-retry-token: ptnCpRJdeyRljPISnfVpUfbWlSJOOb\r\nopc-client-retries: true\r\nopc-client-info: Oracle-PythonSDK/2.64.0\r\nContent-Length: 272\r\ndate: Fri, 22 Apr 2022 15:41:49 GMT\r\nhost: database.us-ashburn-1.oraclecloud.com\r\nx-content-sha256: Ge2970dE5PE7kgJu3d6w/ldkApS4Frcu4lZ/SuTtNHY=\r\nauthorization: Signature algorithm="rsa-sha256",headers="date (request-target) host content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaazq5i3cxpao7ikejs4l65qpxmh3hzdhl4awtkgbvvj5f52x5lean4t/ocid1.user.oc1..aaaaaaaa7ioyebg6iwgakrnsw3odyo2b4bnviqvqa6ewgrikwvabzg36fs7b/61:bf:23:69::be::c2:b6:f1:6428:25:91:a7:e3:917a",signature="PvVJwQcb7jQm4h4wWxqx97cgsHDwWgvCEhUhl8Iz7Vsy3ti/phd04Q9RsTZy7gYdAEIioC+ou4d4ngFDHLvT0YL2y8G6qYncMc0UkvxHdPmAnro3yiLdkHnt7YVfU2rWp8CoUXGywSHb5IMCZUkprQ0NMKDnDkqaYVNDGVM+owtOE7Rk7l3ydemrf5SPtbOccfHSMu6eYrqEWpAwKkvSq5BAO9zTZr8I46iFxnw2IXnIheup5vcnoDobUHX4APW2DhcJ+5LWh1fKDiRYFjwOuDKzsMSq1qxf7BVW9uz3ABmIGTBrmkXTr9fmmUZkpDgHd62ekHSv19FPFAiZH81YAA==",version="1"\r\n\r\n{"targetContainerDatabaseId": "ocid1.database.oc1.iad.anuwcljsnlpusgyxm6m2tfvbrqh7q6utyabotijke2gt7a6a5vciu5ayacsa", "sourceContainerDbAdminPassword": "PA55word-#", "clonedPdbName": "TESTCL", "pdbAdminPassword": "PA55word-#", "targetTdeWalletPassword": "PA55word-#"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Date: Fri, 22 Apr 2022 15:41:50 GMT
header: opc-request-id: 028ECE46D3B842C4A21545386BAE4841/F11DCB4EEBAA96CD92B7DBE218DBB1E5/98C96FFD470BD029CEFA855C8317B650
header: Content-Type: application/json
header: X-Content-Type-Options: nosniff
header: Content-Length: 160
DEBUG:oci.base_client.4415275312: 2022-04-22 15:41:50.226994: time elapsed for request 028ECE46D3B842C4A21545386BAE4841: 0.5268247860949486
DEBUG:oci.base_client.4415275312: 2022-04-22 15:41:50.227136: Response status: 400
DEBUG:oci.base_client.4415275312: 2022-04-22 15:41:50.227231: python SDK time elapsed for deserializing: 9.258976206183434e-06
Traceback (most recent call last):
  File "/Users/JEliker/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci_cli/json_skeleton_utils.py", line 78, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci_cli/cli_util.py", line 837, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/services/database/src/oci_cli_database/database_cli_extended.py", line 247, in remote_clone_pluggable_database_extended
    ctx.invoke(database_cli.remote_clone_pluggable_database, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci_cli/json_skeleton_utils.py", line 78, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci_cli/cli_util.py", line 837, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/services/database/src/oci_cli_database/generated/database_cli.py", line 15221, in remote_clone_pluggable_database
    result = client.remote_clone_pluggable_database(
  File "/usr/local/lib/python3.10/site-packages/oci/database/database_client.py", line 21778, in remote_clone_pluggable_database
    return retry_strategy.make_retrying_call(
  File "/usr/local/lib/python3.10/site-packages/oci/retry/retry.py", line 293, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci/base_client.py", line 472, in call_api
    response = self.request(request, allow_control_chars)
  File "/usr/local/lib/python3.10/site-packages/circuitbreaker.py", line 52, in wrapper
    return self.call(function, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/circuitbreaker.py", line 67, in call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oci/base_client.py", line 601, in request
    self.raise_service_error(request, response, service_code, message)
  File "/usr/local/lib/python3.10/site-packages/oci/base_client.py", line 758, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'opc-request-id': '028ECE46D3B842C4A21545386BAE4841/F11DCB4EEBAA96CD92B7DBE218DBB1E5/98C96FFD470BD029CEFA855C8317B650', 'code': 'InvalidParameter', 'message': 'Admin password of the source Container Database cannot be empty in remote clone pluggable database operation.', 'status': 400}
```

**Comment by KartikShrikantHegde** [comment]
Hi @jeliker , Database eng team has indicated that this issue was fixed in May 2022. Can you please retry the operation and let us know if you are still facing the issue?

Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @jeliker , I am closing this issue, please re-open the ticket if you are still having the issue. Thanks.
