### ISSUE TITLE
AttributeError: module 'interactive.cli_interactive' has no attribute 'start_interactive_mode'

### ISSUE THREAD

**Issue by neilfernandez** [oracle/oci-cli#585]
When I try to upload an object to storage I get this error. It seems to be an error when starting interactive mode in general. If I run
`oci - i` I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 33, in <module>
    sys.exit(load_entry_point('oci-cli==3.15.2', 'console_scripts', 'oci')())
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/oci-cli/3.15.2/libexec/lib/python3.10/site-packages/oci_cli/cli_root.py", line 426, in cli
    cli_interactive.start_interactive_mode(ctx)
AttributeError: module 'interactive.cli_interactive' has no attribute 'start_interactive_mode'. Did you mean: 'start_interactive_shell'?
```

I am on version 3.15.2, and brew will not upgrade to 3.16, it shows as this is the latest there.

**Comment by mandyht** [comment]
3.16.0 is now available on homebrew, and you shouldn't see this error anymore after the version upgrade
