### ISSUE TITLE
create_backup_from_onprem KeyError: 'connection_timeout'

### ISSUE THREAD

**Issue by ClecioCaires** [oracle/oci-cli#611]
Hello,

I'm getting the error KeyError: 'connection_timeout' when I run the command, could anyone help?

[oracle@m-oracle oci-cli-scripts]$ export ORACLE_UNQNAME=HOMOLDBA
[oracle@m-oracle oci-cli-scripts]$ rm -rf /home/oracle/migrate/onprem_upload
[oracle@m-oracle oci-cli-scripts]$ cd /home/oracle/migrate/bin/oci-cli-scripts/
[oracle@m-oracle oci-cli-scripts]$ ./create_backup_from_onprem --config-file /home/oracle/migrate/config.txt --display-name BACKUP_STANDALONE --availability-domain $AD --edition STANDARD_EDITION --opc-installer-dir /home/oracle/migrate --tmp-dir /home/oracle/migrate/onprem_upload --compartment-id $C --rman-password tkx73A12@@
/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/httpsig_cffi/sign.py:10: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend  # noqa: F401
Connecting to Oracle database
Oracle version is:11.2.0.4.0
Checking the archive log mode of the database
Checking if the database is open
Getting database name and database unique name
Database Id:3877817354 Name:HOMOLDBA UniqueName:HOMOLDBA
Fetching character set
Character Set:WE8MSWIN1252
Fetching national character set
National Character Set:AL16UTF16
Fetching rac mode
Rac mode:FALSE
Traceback (most recent call last):
  File "./create_backup_from_onprem", line 8, in <module>
    sys.exit(create_backup_from_onprem())
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/scripts/database/dbaas.py", line 280, in create_backup_from_onprem
    client = cli_util.build_client('database', 'database', ctx)
  File "/home/oracle/migrate/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/cli_util.py", line 552, in build_client
    if ctx.obj['connection_timeout']:
KeyError: 'connection_timeout'

**Comment by nmjunghare** [comment]
I am also getting same error message not able to complete the backup onprem script.

[oracle@srv1 oci-cli-scripts]$ ./create_backup_from_onprem --config-file /home/oracle/.oci/config --profile DEFAULT --display-name oradb --availability-domain $AD --edition ENTERPRISE_EDITION_HIGH_PERFORMANCE --opc-installer-dir /home/oracle/oci --tmp-dir /home/oracle/oci/onprem_upload --compartment-id $C
/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/oci/_vendor/httpsig_cffi/sign.py:10: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend  # noqa: F401
Connecting to Oracle database
Oracle version is:19.0.0.0.0
Checking the archive log mode of the database
Checking if the database is open
Getting database name and database unique name
Database Id:2940187580 Name:ORADB UniqueName:oradb
Fetching character set
Character Set:AL32UTF8
Fetching national character set
National Character Set:AL16UTF16
Fetching rac mode
Rac mode:FALSE
Traceback (most recent call last):
  File "./create_backup_from_onprem", line 8, in <module>
    sys.exit(create_backup_from_onprem())
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/scripts/database/dbaas.py", line 281, in create_backup_from_onprem
    client = cli_util.build_client('database', 'database', ctx)
  File "/home/oracle/oci/lib/oracle-cli/lib64/python3.6/site-packages/oci_cli/cli_util.py", line 578, in build_client
    if ctx.obj['connection_timeout']:
KeyError: 'connection_timeout'
[oracle@srv1 oci-cli-scripts]$

**Comment by nmjunghare** [comment]
In the build_client function of cli_util.py, locate and fix the relevant part like this:

if 'connection_timeout' not in ctx.obj:
    ctx.obj['connection_timeout'] = 60  # Default to 60 seconds

if ctx.obj['connection_timeout']:
    if 'read_timeout' in ctx.obj and ctx.obj['read_timeout']:
        client.base_client.timeout = (ctx.obj['connection_timeout'], ctx.obj['read_timeout'])
    else:
        client.base_client.timeout = (ctx.obj['connection_timeout'], client.base_client.timeout[1])
else:
    if 'read_timeout' in ctx.obj and ctx.obj['read_timeout']:
        client.base_client.timeout = (client.base_client.timeout[0], ctx.obj['read_timeout'])


./create_backup_from_onprem --config-file /home/oracle/.oci/config --profile DEFAULT --display-name oradb --availability-domain $AD --edition ENTERPRISE_EDITION_HIGH_PERFORMANCE --opc-installer-dir /home/oracle/oci/opc_installer/opc_installer --tmp-dir /home/oracle/oci/onprem_upload --compartment-id $C
