### ISSUE TITLE
Installing oci-cli on S11.4 SRU51 failing

### ISSUE THREAD

**Issue by skinkel** [oracle/oci-cli#637]
Hello,

The setup is:

no proxy, no certs needed
S11.4.51.132.1 i86pc
gcc version 12.1.0
Python 3.7.14
pip 20.3.4 from /usr/lib/python3.7/vendor-packages/pip (python 3.7)
try oci-cli v3.2.1 until v3.22.4
install command: ./install.sh --oci-cli-version 3.22.4 (as well just install.sh)

[...]
Collecting cryptography<39.0.0,>=3.2.1
  Downloading cryptography-38.0.4.tar.gz (599 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.8/599.8 kB 6.6 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
 
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
[...]
Building wheels for collected packages: cffi
        Building wheel for cffi (setup.py): started
        Building wheel for cffi (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
[...]
 gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -DPIC -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -D_REENTRANT -m64 -fPIC -DPIC -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/root/lib/oracle-cli/include -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.solaris-2.11-i86pc.64bit-3.7/c/_cffi_backend.o
            c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
               15 | #include <ffi.h>
                  |          ^~~~~~~
            compilation terminated.
            error: command 'gcc' failed with exit status 1
[...]
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
        Running setup.py clean for cffi
      Failed to build cffi
      Installing collected packages: wheel, typing-extensions, setuptools, semantic-version, pycparser, setuptools-rust, cffi
        Running setup.py install for cffi: started
        Running setup.py install for cffi: finished with status 'error'
        error: subprocess-exited-with-error
 
        × Running setup.py install for cffi did not run successfully.
        │ exit code: 1
[...]
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -DPIC -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -D_REENTRANT -m64 -fPIC -DPIC -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/root/lib/oracle-cli/include -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.solaris-2.11-i86pc.64bit-3.7/c/_cffi_backend.o
            c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
               15 | #include <ffi.h>
                  |          ^~~~~~~
            compilation terminated.
            error: command 'gcc' failed with exit status 1
            [end of output]
 
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
 
      × Encountered error while trying to install package.
      ╰─> cffi
[...]
note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_dbeF", line 743, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_dbeF", line 697, in main
    install_cli(install_dir, tmp_dir, cli_version, OPTIONAL_FEATURES, dependency_dir)
  File "/tmp/oci_cli_install_tmp_dbeF", line 327, in install_cli
    exec_command(cmd, env=env)
 File "/tmp/oci_cli_install_tmp_dbeF", line 145, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmpgfj10vzx', 'oci_cli==3.22.4', '--upgrade']' returned non-zero exit status 1.
[...]

Any idea what's up here ?
Any hints are welcome.

Thanks
Stefan
[Installing_oci-cli_on_S11.4_SRU51_failing.txt](https://github.com/oracle/oci-cli/files/10699402/Installing_oci-cli_on_S11.4_SRU51_failing.txt)

**Comment by skinkel** [comment]
It works on the following Solaris setup:

U20 x86 S11.4 SRU 51
pip 20.3.4 
Python 3.7.14 
gcc version 12.1.0 (GCC)
no proxy, no certs
offline installation

Using from oci-cli-3.22.5.zip from https://github.com/oracle/oci-cli/releases.

root@ap513809:/oci_cli/oci-cli# pip-3.7 install oci_cli-3.22.5-py3-none-any.whl
Processing ./oci_cli-3.22.5-py3-none-any.whl
...
Requirement already satisfied: cryptography<39.0.0,>=3.2.1 in /usr/lib/python3.7/vendor-packages (from oci-cli==3.22.5) (37.0.2)
[…]

[…]
Collecting cryptography<39.0.0,>=3.2.1
  Downloading cryptography-38.0.4.tar.gz (599 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.8/599.8 kB 6.9 MB/s eta 0:00:00
  Installing build dependencies ... error]
...
Collecting cryptography<39.0.0,>=3.2.1
  Downloading cryptography-13.0.2.tar.gz (599 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.8/599.8 kB 6.9 MB/s eta 0:00:00
