### ISSUE TITLE
Not able to Install on Red Hat Enterprise Linux release 8.7  ERROR: No matching distribution found for setuptools>=40.8.0

### ISSUE THREAD

**Issue by abavera** [oracle/oci-cli#671]
cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.7 (Ootpa)

Downloaded:
for LINUX -8
wget https://github.com/oracle/oci-cli/releases/download/v3.25.4/oci-cli-3.25.4-CentOS-8-Offline.zip

bash install.sh --offline-install

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Starting OCI CLI Offline Installation
Running install script.
python3 ./install.py  --offline-install
-- Verifying Python version.
-- Python version 3.9.13 okay.

===> In what directory would you like to place the install? (leave blank to use '/root/lib/oracle-cli'): 
-- Install directory '/root/lib/oracle-cli' is not empty and may contain a previous installation.

===> Remove this directory? (y/N): y
-- Deleted '/root/lib/oracle-cli'.
-- Creating directory '/root/lib/oracle-cli'.
-- We will install at '/root/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/root/bin'): 
-- The executable will be in '/root/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/root/bin/oci-cli-scripts'): 
-- The scripts will be in '/root/bin/oci-cli-scripts'.
-- Trying to use python3 venv.
-- Executing: ['/bin/python3', '-m', 'venv', '/root/lib/oracle-cli']
-- Executing: ['/root/lib/oracle-cli/bin/pip', 'install', 'pip', '--upgrade', '--find-links', 'cli-deps', '--no-index']
Looking in links: cli-deps
Processing ./cli-deps/pip-23.1.2-py3-none-any.whl
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-23.1.2
-- Executing: ['/root/lib/oracle-cli/bin/pip', 'install', 'oci_cli', '--find-links', 'cli-deps/python39.html', '--no-index', '--ignore-requires-python']
Looking in links: cli-deps/python39.html
Processing ./cli-deps/oci_cli-3.25.4-py3-none-any.whl
Processing ./cli-deps/oci-2.99.1-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/arrow-1.2.3-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/certifi-2022.12.7-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/click-8.0.4-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/cryptography-39.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (from oci_cli)
Processing ./cli-deps/jmespath-0.10.0-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/python_dateutil-2.8.2-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/pytz-2023.3-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/six-1.16.0-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/terminaltables-3.1.0.tar.gz (from oci_cli)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  Ã— pip subprocess to install build dependencies did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [3 lines of output]
      Looking in links: cli-deps/python39.html
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— pip subprocess to install build dependencies did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/root/scripts/OCI_CLI/oci-cli-installation/./install.py", line 752, in <module>
    main()
  File "/root/scripts/OCI_CLI/oci-cli-installation/./install.py", line 705, in main
    install_cli(install_dir, tmp_dir, cli_version, OPTIONAL_FEATURES, dependency_dir)
  File "/root/scripts/OCI_CLI/oci-cli-installation/./install.py", line 335, in install_cli
    exec_command(cmd, env=env)
  File "/root/scripts/OCI_CLI/oci-cli-installation/./install.py", line 153, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/lib/oracle-cli/bin/pip', 'install', 'oci_cli', '--find-links', 'cli-deps/python39.html', '--no-index', '--ignore-requires-python']' returned non-zero exit status 1.
===================

**Comment by abavera** [comment]
update-alternatives --list
libnssckbi.so.x86_64  auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                manual  /usr/bin/python3.8
ifup                  auto    /etc/sysconfig/network-scripts/ifup
cifs-idmap-plugin     auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
python3               manual  /usr/bin/python3.9
ksh                   auto    /usr/bin/ksh93
ld                    auto    /usr/bin/ld.bfd
mta                   auto    /usr/sbin/sendmail.postfix
nmap                  auto    /usr/bin/ncat
pip                   auto    /usr/bin/pip3

**Comment by abavera** [comment]
/root/lib/oracle-cli/bin/pip install oci_cli --find-links cli-deps/python39.html --no-index --ignore-requires-python
Looking in links: cli-deps/python39.html
Processing ./cli-deps/oci_cli-3.25.4-py3-none-any.whl
Processing ./cli-deps/oci-2.99.1-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/arrow-1.2.3-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/certifi-2022.12.7-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/click-8.0.4-py3-none-any.whl (from oci_cli)
Processing ./cli-deps/cryptography-39.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (from oci_cli)
Processing ./cli-deps/jmespath-0.10.0-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/python_dateutil-2.8.2-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/pytz-2023.3-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/six-1.16.0-py2.py3-none-any.whl (from oci_cli)
Processing ./cli-deps/terminaltables-3.1.0.tar.gz (from oci_cli)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  Ã— pip subprocess to install build dependencies did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [3 lines of output]
      Looking in links: cli-deps/python39.html
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— pip subprocess to install build dependencies did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gbm777** [comment]
same problem
