### ISSUE TITLE
Creates an instance pool.  Response status: 500

### ISSUE THREAD

**Issue by augusl** [oracle/oci-cli#678]
### Usage
`oci compute-management instance-pool create --compartment-id <COMPARTMENT_OCID> --instance-configuration-id <INSTANCE_CONFIGURATION_OCID> --placement-configurations '[{"availabilityDomain":"rMQh:PHX-AD-1","primarySubnetId":"<PRIMARY_SUBNET_OCID>","secondaryVnicSubnets":[{"displayName":"<displayName>","subnetId":"<subnetId>"}]}]' --size 2 --display-name test-oci-1 --debug`

**Comment by augusl** [comment]
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Date: Wed, 17 May 2023 06:41:05 GMT
header: opc-request-id: 27DD34890780477888232C13D4728AB4/7549AC752E851942A5D215B914B1AF8D/D127FBF5D5428306AC2E41FE6051D3F8
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: Content-Type: application/json
header: X-Content-Type-Options: nosniff
header: Content-Length: 89
DEBUG:oci.base_client.4376166288: 2023-05-17 06:41:04.639383: time elapsed for request 27DD34890780477888232C13D4728AB4: 2.0853532049950445
DEBUG:oci.base_client.4376166288: 2023-05-17 06:41:04.639596: Response status: 500
DEBUG:oci.base_client.4376166288: 2023-05-17 06:41:04.639818: python SDK time elapsed for deserializing: 2.2245003492571414e-05
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 33, in <module>
    sys.exit(load_entry_point('oci-cli==3.27.1', 'console_scripts', 'oci')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci_cli/json_skeleton_utils.py", line 78, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci_cli/cli_util.py", line 874, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/services/core/src/oci_cli_compute_management/generated/computemanagement_cli.py", line 554, in create_instance_pool
    result = client.create_instance_pool(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci/core/compute_management_client.py", line 985, in create_instance_pool
    return retry_strategy.make_retrying_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci/base_client.py", line 531, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci/base_client.py", line 716, in request
    self.raise_transient_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/usr/local/Cellar/oci-cli/3.27.1/libexec/lib/python3.11/site-packages/oci/base_client.py", line 890, in raise_transient_service_error
    raise exceptions.TransientServiceError(
oci.exceptions.TransientServiceError: {'target_service': 'compute_management', 'status': 500, 'code': 'InternalError', 'opc-request-id': '27DD34890780477888232C13D4728AB4/7549AC752E851942A5D215B914B1AF8D/D127FBF5D5428306AC2E41FE6051D3F8', 'message': 'An internal error occurred. Please retry.', 'operation_name': 'create_instance_pool', 'timestamp': '2023-05-17T06:41:04.639698+00:00', 'client_version': 'Oracle-PythonSDK/2.102.0', 'request_endpoint': 'POST https://iaas.us-phoenix-1.oraclecloud.com/20160918/instancePools', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_500__500_internalerror for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/InstancePool/CreateInstancePool for details on this operation's requirements. If you are unable to resolve this compute_management issue, please contact Oracle support and provide them this full error message."}
