### ISSUE TITLE
oci cli 3.34.0 is broken badly (installed using brew)

### ISSUE THREAD

**Issue by spareslant** [oracle/oci-cli#720]
I upgraded oci cli today using brew , and new version of oci-cli is not working.

```
$ brew info  oci-cli
==> oci-cli: stable 3.34.0 (bottled), HEAD
Oracle Cloud Infrastructure CLI
https://docs.cloud.oracle.com/iaas/Content/API/Concepts/cliconcepts.htm
/usr/local/Cellar/oci-cli/3.34.0 (28,618 files, 322.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-10-18 at 09:21:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/oci-cli.rb
License: UPL-1.0 or Apache-2.0
==> Dependencies
Required: cffi ✔, python-certifi ✔, python-click ✔, python-cryptography ✔, python-pytz ✔, python@3.12 ✔, pyyaml ✔, six ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 2,977 (30 days), 9,050 (90 days), 19,062 (365 days)
install-on-request: 2,977 (30 days), 9,048 (90 days), 19,063 (365 days)
build-error: 0 (30 days)
```

```
$ python --version
Python 3.11.6

$ python -c 'import pytz; print("Import successfull")'
Import successfull
```

```
$ oci --version
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci_cli/__init__.py", line 9, in <module>
    from oci import fips  # noqa: F401,E402
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/__init__.py", line 5, in <module>
    from . import auth, config, constants, decorators, exceptions, regions, pagination, retry, fips, circuit_breaker, alloy
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/auth/__init__.py", line 6, in <module>
    from . import certificate_retriever  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/auth/certificate_retriever.py", line 9, in <module>
    from oci.exceptions import ServiceError
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/exceptions.py", line 6, in <module>
    import oci.util
  File "/usr/local/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/util.py", line 14, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```
OS: MacOS Ventura 13.5.2

**Comment by karthik-k-kamath** [comment]
Hi, can you try one of these upgrade steps mentioned here, to rule out nay local issues: 
[Upgrading the CLI](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliupgrading.htm)

If you still face error, then I recommend installing CLI in a separate virtual environment using: 
[Manual Installation](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/climanualinst.htm#climanualinst_intro)

**Comment by raducr** [comment]
It happens to me too. Brand new oci-cli installation using brew, but different modlue in error: six

```
$ brew info oci-cli
==> oci-cli: stable 3.34.0 (bottled), HEAD
Oracle Cloud Infrastructure CLI
https://docs.cloud.oracle.com/iaas/Content/API/Concepts/cliconcepts.htm
/opt/homebrew/Cellar/oci-cli/3.34.0 (28,659 files, 323.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-10-18 at 15:13:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/oci-cli.rb
License: UPL-1.0 or Apache-2.0
==> Dependencies
Required: cffi ✔, python-certifi ✔, python-click ✔, python-cryptography ✔, python-pytz ✔, python@3.12 ✔, pyyaml ✔, six ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 3,000 (30 days), 9,067 (90 days), 19,088 (365 days)
install-on-request: 2,999 (30 days), 9,066 (90 days), 19,089 (365 days)
build-error: 0 (30 days)
```

```
$ python3 --version
Python 3.12.0
```

```
$ oci --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci_cli/__init__.py", line 9, in <module>
    from oci import fips  # noqa: F401,E402
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/__init__.py", line 5, in <module>
    from . import auth, config, constants, decorators, exceptions, regions, pagination, retry, fips, circuit_breaker, alloy
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/pagination/__init__.py", line 5, in <module>
    from .pagination_utils import list_call_get_all_results, list_call_get_up_to_limit, list_call_get_all_results_generator, list_call_get_up_to_limit_generator
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/pagination/pagination_utils.py", line 5, in <module>
    from .. import dns, object_storage
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/dns/__init__.py", line 10, in <module>
    from .dns_client import DnsClient
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/dns/dns_client.py", line 13, in <module>
    from oci.base_client import BaseClient
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/oci/base_client.py", line 24, in <module>
    from dateutil.parser import parse
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/opt/homebrew/Cellar/oci-cli/3.34.0/libexec/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 42, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

OS: MacOS Ventura 13.5.2

**Comment by raducr** [comment]
Installing CLI in a separate virtual environment worked for me

**Comment by spareslant** [comment]
It works when installed using pip. But broken using brew . Is brew installation not supported anymore ?

**Comment by Djelibeybi** [comment]
This seems to be an issue with Homebrew itself. Can you please try `brew reinstall oci-cli`? The Homebrew folks have bumped the Python dependency to 3.12 but Homebrew hasn't reinstalled all the necessary dependencies.

**Comment by liefra** [comment]
This workaround worked for me. Thanks

**Comment by Djelibeybi** [comment]
Awesome. I'm going to close this issue so if anyone has any further problems, please open a new one.
