### ISSUE TITLE
Add support for Python 3.12, install.sh fails (distutils module removed)

### ISSUE THREAD

**Issue by veny** [oracle/oci-cli#778]
[distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is removed in Python 3.12.

install.sh fails with following message:
```
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_gdAY", line 722, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_gdAY", line 705, in main
    venv_site_packages_directory = subprocess.check_output([venv_python_executable, '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']).strip()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/oci-cli-3.41.0/bin/python', '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']' returned non-zero exit status 1.
```

**Comment by zeroows** [comment]
Any Update on this?

**Comment by karthik-k-kamath** [comment]
Hi, we (CLI team) is planning to add support for Python 3.12, in next couple of months, which should address this issue.
Closing this issue for now as CLI only supports till Python 3.11

**Comment by 12345ieee** [comment]
I understand taking your time for a proper python 3.12 support, but would it be possible to just add a `pip install setuptools` in the venv to just get past this step?

I have the cli half installed in a python 3.12 machine (like many others), it looks working, I'd appreciate if the install process could progress ASAP as far as it can if the fixes are simple.

Thanks.

**Comment by karthik-k-kamath** [comment]
Thanks Andrea for the suggestions. I will check with the team if this can be brought in faster

**Comment by karthik-k-kamath** [comment]
Yes Natan, please do.

**Comment by kaiucosta** [comment]
alguma previsão para aplicar a sugestão do @12345ieee ?

**Comment by karthik-k-kamath** [comment]
I will check with team and come back on the possibility of providing an earlier fix

**Comment by brasrox** [comment]
ubuntu 24.04 have py 3.12.3 
install of oci cli breaks in 
**pip install setuptools** doesnot work too

**Comment by damntourists** [comment]
I am also having this issue. Install script reports that Python 3.12 is OK 
```
[ ... ]
-- Verifying Python version.
-- Python version 3.12.3 okay.
[ ... ]
Installing collected packages: wcwidth, pytz, circuitbreaker, types-python-dateutil, terminaltables, six, PyYAML, pycparser, prompt-toolkit, jmespath, click, certifi, python-dateutil, cffi, cryptography, arrow, pyOpenSSL, oci, oci_cli
Successfully installed PyYAML-6.0.1 arrow-1.3.0 certifi-2024.8.30 cffi-1.17.1 circuitbreaker-2.0.0 click-8.0.4 cryptography-42.0.8 jmespath-0.10.0 oci-2.135.1 oci_cli-3.48.2 prompt-toolkit-3.0.43 pyOpenSSL-24.2.1 pycparser-2.22 python-dateutil-2.9.0.post0 pytz-2024.2 six-1.16.0 terminaltables-3.1.10 types-python-dateutil-2.9.0.20240906 wcwidth-0.2.13
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_HxSR", line 722, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_HxSR", line 705, in main
    venv_site_packages_directory = subprocess.check_output([venv_python_executable, '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']).strip()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/brett/lib/oracle-cli/bin/python', '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']' returned non-zero exit status 1.
```
Can we reopen this issue?
